### ISSUE TITLE
Support .net 451

### ISSUE THREAD

**Issue by sphiecoh** [lynxx131/dotnet.microservice#3]
Is there a reason why you dropped support for net451?

**Comment by Sphiecoh** [comment]
I see why NVM

**Comment by lynxx131** [comment]
I removed net451 because of Microsoft end of support announcement for .NET 4.5.1. and I am currently targeting net46 for my .NET Framework based projects so it has only just come to my mind that I have actually broken .NET 4.5.2 targeting which is still a supported MS release.

I'll clean up the targeting so that net45, net451 and net452 will work correctly. I should hopefully be able to push a new release version with these targeting changes tomorrow afternoon.

**Comment by lynxx131** [comment]
Version 1.1.3 on Nuget now supports .NET 4.5.1
